import { Poppins } from "next/font/google";
import "./globals.css";
import cx from "classnames";
import { poppins } from "./fonts/index";
import Header from "../app/componens/layout/header";
import Sidebar from "../app/componens/layout/sidebar";
import Bottombar from "./componens/layout/bottom_bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cx(poppins, poppins.className)}>
        <div className="flex">
          <Sidebar />
          <Header />
        </div>
        {children}
        <Bottombar />
      </body>
    </html>
  );
}
